version: '3.8'

services:
  coolify:
    image: coollabsio/coolify
    container_name: coolify
    restart: always
    ports:
      - "8280:8000"
      - "8282:80"
      - "8443:443"
      - "6001:6001"
      - "6002:6002"
      - "9122:22"
    volumes:
      - coolify-data:/app/data
      - coolify-ssl:/app/ssl
    environment:
      - DATABASE_URL=postgresql://coolify:strongpassword@coolify-db:5432/coolify
      - COOLIFY_HOSTNAME=fmpdevelop.sytes.net
      - COOLIFY_IS_HTTPS=false
      - COOLIFY_SECRET_KEY=Pollito123.
      - REDIS_HOST=coolify-redis
      - REDIS_PORT=6379
    depends_on:
      - coolify-db
      - coolify-redis

  coolify-db:
    image: postgres:15
    container_name: coolify-db
    restart: always
    environment:
      POSTGRES_DB: coolify
      POSTGRES_USER: coolify
      POSTGRES_PASSWORD: strongpassword
    volumes:
      - pgdata:/var/lib/postgresql/data

  coolify-redis:
    image: redis:alpine
    container_name: coolify-redis
    restart: always
    volumes:
      - redisdata:/data

volumes:
  coolify-data:
  coolify-ssl:
  pgdata:
  redisdata:
