version: '3'
services:
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
      - "8980:80"
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=host.docker.internal
      - PMA_PORT=3306
    restart: always
