version: '3.8'

services:
  minio:
    image: quay.io/minio/minio
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: username
      MINIO_SECRET_KEY: administrator
    volumes:
      - minio_data:/data
    ports:
      - "9000:9000"
      - "9090:9090"
    
    command: server /data --console-address ":9090"

volumes:
  minio_data:


